// This file is generated by scripts/generate-base-path.js during `npm run build`.
// Do not edit manually; re-run `npm run build` to update it.
// The version committed to git contains the default (empty string = root) used
// during development and testing. Deployments with VOLODYSLAV_BASEURL set will
// have this file overwritten by the build step with the correct path prefix.

/**
 * The base path prefix extracted from VOLODYSLAV_BASEURL at build time.
 * Empty string means the app is served from root.
 * @type {string}
 */
const BASE_PATH_PREFIX = "";

module.exports = { BASE_PATH_PREFIX };
