/**
 * Controller hook for live diary questioning display state.
 *
 * Manages the display of live diary questions that arrive from the backend
 * as a side-effect of push-audio calls.  All transcription, recombination,
 * and question generation are handled server-side; this hook only owns the
 * client-side presentation state.
 *
 * Questions are retrieved by polling GET /audio-recording-session/:sessionId/live-questions
 * every POLLING_INTERVAL_MS milliseconds while recording is active.
 *
 * @module useDiaryLiveQuestioningController
 */

import { useState, useRef, useCallback, useEffect } from "react";
import { getLiveQuestions } from "./session_api.js";

/** @typedef {import('./session_api.js').DiaryQuestion} DiaryQuestion */

/**
 * How often (in ms) to poll the backend for newly generated diary questions.
 */
const POLLING_INTERVAL_MS = 5000;

/**
 * @typedef {object} QuestionGeneration
 * @property {string} generationId - Unique identifier for this generation.
 * @property {number} milestoneNumber - Chunk sequence number that produced this generation.
 * @property {DiaryQuestion[]} questions - List of questions in this generation.
 */

/**
 * @typedef {object} UseDiaryLiveQuestioningControllerResult
 * @property {QuestionGeneration[]} displayedGenerations - Question generations, newest first.
 * @property {(questions: DiaryQuestion[], milestoneNumber: number) => void} onQuestions - Call with questions from each push-audio response and its fragment sequence number.
 * @property {(sessionId: string) => void} startLive - Reset display state and begin polling for a new recording session.
 * @property {() => void} stopLive - Stop accepting new questions and stop polling.
 */

const MAX_VISIBLE_GENERATIONS = 4;

/**
 * Monotonically increasing counter for unique generation IDs.
 * Module-level so it persists across hook instances within the same page load.
 */
let _generationCounter = 0;

/**
 * Generate a simple unique ID for a generation.
 * @param {number} milestoneNumber
 * @returns {string}
 */
function makeGenerationId(milestoneNumber) {
    _generationCounter += 1;
    return `gen-${milestoneNumber}-${_generationCounter}`;
}

/** @returns {UseDiaryLiveQuestioningControllerResult} */
export function useDiaryLiveQuestioningController() {
    const [displayedGenerations, setDisplayedGenerations] = useState(
        /** @returns {QuestionGeneration[]} */ () => []
    );

    /** @type {React.MutableRefObject<boolean>} */
    const isRunningRef = useRef(false);
    /** @type {React.MutableRefObject<string>} */
    const currentSessionIdRef = useRef("");
    /** @type {React.MutableRefObject<ReturnType<typeof setInterval> | null>} */
    const pollingIntervalRef = useRef(null);
    /** @type {React.MutableRefObject<number>} */
    const pollingCounterRef = useRef(0);
    /** @type {React.MutableRefObject<boolean>} */
    const isPollInFlightRef = useRef(false);

    /**
     * Called with questions returned from push-audio or from polling.
     * Adds a new generation to the display (newest first, max 4).
     */
    const onQuestions = useCallback(
        /**
         * @param {DiaryQuestion[]} questions
         * @param {number} milestoneNumber
         */
        (questions, milestoneNumber) => {
            if (!isRunningRef.current || !questions || questions.length === 0) {
                return;
            }

            const generation = {
                generationId: makeGenerationId(milestoneNumber),
                milestoneNumber,
                questions,
            };

            setDisplayedGenerations((prev) => {
                const updated = [generation, ...prev];
                return updated.slice(0, MAX_VISIBLE_GENERATIONS);
            });
        },
        []
    );

    /**
     * Start live questioning for a new recording session.
     * Resets display state and begins polling for questions.
     * @param {string} sessionId
     */
    const startLive = useCallback(
        /** @param {string} sessionId */
        (sessionId) => {
            isRunningRef.current = true;
            currentSessionIdRef.current = sessionId;
            setDisplayedGenerations([]);

            // Start polling for questions generated by background AI processing.
            if (pollingIntervalRef.current !== null) {
                clearInterval(pollingIntervalRef.current);
            }
            pollingIntervalRef.current = setInterval(async () => {
                if (!isRunningRef.current || !currentSessionIdRef.current) {
                    return;
                }
                // Skip if a previous poll is still in flight to prevent overlapping executions.
                if (isPollInFlightRef.current) {
                    return;
                }
                isPollInFlightRef.current = true;
                try {
                    const questions = await getLiveQuestions(currentSessionIdRef.current);
                    if (questions.length > 0 && isRunningRef.current) {
                        pollingCounterRef.current += 1;
                        onQuestions(questions, pollingCounterRef.current);
                    }
                } catch {
                    // Polling failure is best-effort; recording continues unaffected.
                } finally {
                    isPollInFlightRef.current = false;
                }
            }, POLLING_INTERVAL_MS);
        },
        [onQuestions]
    );

    /**
     * Stop live questioning. New questions will be ignored and polling stops.
     */
    const stopLive = useCallback(() => {
        isRunningRef.current = false;
        currentSessionIdRef.current = "";
        if (pollingIntervalRef.current !== null) {
            clearInterval(pollingIntervalRef.current);
            pollingIntervalRef.current = null;
        }
    }, []);

    // Cleanup polling interval on unmount.
    useEffect(() => {
        return () => {
            if (pollingIntervalRef.current !== null) {
                clearInterval(pollingIntervalRef.current);
            }
        };
    }, []);

    return {
        displayedGenerations,
        onQuestions,
        startLive,
        stopLive,
    };
}
