/**
 * Key encoding and value serialisation module for the incremental-graph database.
 *
 * This module owns all the logic that converts between the two representations
 * of a database snapshot entry:
 *
 *   - Raw LevelDB key/value pairs (what the database stores)
 *   - Filesystem path/content pairs  (what the snapshot directory stores)
 *
 * Key encoding
 * ------------
 * LevelDB sublevel keys are structured as:
 *
 *   !namespace!!sublevel!{"head":"all_events","args":[]}
 *
 * The `!!` separator marks the boundary between nested sublevel names.
 * The actual stored key follows after the last `!` in the prefix chain.
 *
 * Two types of stored key exist in this database:
 *
 *   1. Structured JSON keys (data sublevels: values, freshness, inputs, revdeps,
 *      counters, timestamps):
 *        {"head":"event","args":["abc"]}
 *      Encoded as: namespace/sublevel/event/abc
 *
 *   2. Plain string keys (meta sublevels: _meta, meta):
 *        format, version
 *      Encoded as: namespace/sublevel/format
 *
 * Argument encoding
 * -----------------
 * String arguments are percent-encoded: `/` → `%2F`, `%` → `%25`,
 * `!` → `%21` (critical for bijection since `!` is the LevelDB separator).
 * Non-string arguments (numbers, booleans, arrays, objects) are JSON-encoded
 * and prefixed with `~` to distinguish them from plain strings.
 *
 * Value serialisation
 * -------------------
 * Database values are serialised to JSON text when written to files
 * (serializeValue) and parsed back from JSON text when read (parseValue).
 * Centralising both operations here means that render.js and scan.js contain
 * no JSON operations at all.
 *
 * Bijection guarantee
 * -------------------
 * For all keys generated by this database, keyToRelativePath and
 * relativePathToKey are exact inverses:
 *   relativePathToKey(keyToRelativePath(key)) === key
 */

/**
 * Sublevel names that store plain string keys rather than structured JSON keys.
 * @type {Set<string>}
 */
const PLAIN_KEY_SUBLEVELS = new Set(['_meta', 'meta']);

/**
 * Prefix used to distinguish non-string arguments from plain strings.
 * A path segment starting with '~' holds a JSON-encoded non-string value.
 */
const NON_STRING_ARG_PREFIX = '~';
const ESCAPED_STRING_ARG_PREFIX = NON_STRING_ARG_PREFIX + NON_STRING_ARG_PREFIX;

// Use uppercase sentinels as the canonical on-disk form for literal '.' and '..'
// segments so renderToFilesystem() is deterministic; decode accepts lowercase
// too so scanFromFilesystem() stays tolerant of manually created snapshots.
const DOT_SEGMENT_SENTINEL = '%2E';
const DOT_DOT_SEGMENT_SENTINEL = '%2E%2E';
const DOT_SEGMENT_PATTERN = /^%2e$/i;
const DOT_DOT_SEGMENT_PATTERN = /^%2e%2e$/i;

/**
 * Parses a raw LevelDB key into its sublevel names and key content.
 *
 * Raw key format: `!sub1!!sub2!...!subN!keyContent`
 *
 * Algorithm:
 *   1. Strip the leading `!`.
 *   2. Split on `!!` — all segments but the last are pure sublevel names.
 *   3. Split the last segment on the FIRST `!` to separate the deepest
 *      sublevel name from the key content.  This preserves any `!` characters
 *      that may appear inside the key content itself.
 *
 * @param {string} rawKey
 * @returns {{ sublevels: string[], keyContent: string }}
 * @throws {Error} If rawKey does not match the expected `!sublevels!key` format.
 */
function parseRawKey(rawKey) {
    if (!rawKey.startsWith('!')) {
        throw new Error(
            `Invalid database key '${rawKey}': expected raw LevelDB keys to start with '!'`
        );
    }

    /** @type {string[]} */
    const sublevels = [];
    let current = '';
    let i = 1;
    while (i < rawKey.length) {
        const character = rawKey[i];
        if (character === '!') {
            const nextCharacter = i + 1 < rawKey.length ? rawKey[i + 1] : '';
            if (current === '') {
                throw new Error(
                    `Invalid database key '${rawKey}': sublevel names must not be empty.`
                );
            }
            if (nextCharacter === '!') {
                sublevels.push(current);
                current = '';
                i += 2;
                continue;
            } else {
                sublevels.push(current);
                return { sublevels, keyContent: rawKey.slice(i + 1) };
            }
        } else {
            current += character;
        }
        i += 1;
    }

    throw new Error(
        `Invalid database key '${rawKey}': expected a '!' separator before key content.`
    );
}

/**
 * Reconstructs a raw LevelDB key from its sublevel names and key content.
 * Inverse of parseRawKey().
 *
 * @param {string[]} sublevels - Ordered list of sublevel names.
 * @param {string} keyContent - The raw stored key content.
 * @returns {string}
 */
function buildRawKey(sublevels, keyContent) {
    return '!' + sublevels.join('!!') + '!' + keyContent;
}

/**
 * Percent-encodes a plain string for use as a single filesystem path segment.
 * Encodes `%` first to avoid double-encoding, then `/` and `!`.
 * Segments that are exactly `.` or `..` are mapped to sentinels so they never
 * become literal filesystem traversal segments.
 * @param {string} s
 * @returns {string}
 */
function encodeSegment(s) {
    if (s === '.') {
        return DOT_SEGMENT_SENTINEL;
    }
    if (s === '..') {
        return DOT_DOT_SEGMENT_SENTINEL;
    }
    // Encode '%' first to prevent double-encoding (e.g. '/' → '%2F' → '%252F').
    return s.replace(/%/g, '%25').replace(/\//g, '%2F').replace(/!/g, '%21');
}

/**
 * Decodes a percent-encoded path segment back to the original string.
 * @param {string} s
 * @returns {string}
 */
function decodeSegment(s) {
    // Accept either uppercase or lowercase sentinels when scanning a
    // filesystem snapshot, even though encodeSegment() always emits the
    // uppercase canonical sentinels defined above, so manually created
    // snapshots can still be imported reliably.
    if (DOT_SEGMENT_PATTERN.test(s)) {
        return '.';
    }
    if (DOT_DOT_SEGMENT_PATTERN.test(s)) {
        return '..';
    }
    return s.replace(/%21/gi, '!').replace(/%2F/gi, '/').replace(/%25/gi, '%');
}

/**
 * Encodes a single key argument value as a filesystem path segment.
 *
 * String arguments are percent-encoded directly.
 * Non-string arguments (number, boolean, null, array, object) are
 * JSON-serialized and prefixed with NON_STRING_ARG_PREFIX (`~`) so they
 * can be distinguished from plain strings during decoding.
 *
 * @param {unknown} arg - A key argument value.
 * @returns {string}
 */
function encodeArg(arg) {
    if (typeof arg === 'string') {
        if (arg.startsWith(NON_STRING_ARG_PREFIX)) {
            // Escape a leading '~' in string args so "~42" stays distinct from
            // the encoded non-string number 42, which is also prefixed with '~'.
            return ESCAPED_STRING_ARG_PREFIX + encodeSegment(arg.slice(1));
        }
        return encodeSegment(arg);
    }
    return NON_STRING_ARG_PREFIX + encodeSegment(JSON.stringify(arg));
}

/**
 * Decodes a path segment back to a key argument value.
 * Inverse of encodeArg().
 *
 * @param {string} segment
 * @returns {unknown}
 */
function decodeArg(segment) {
    if (segment.startsWith(ESCAPED_STRING_ARG_PREFIX)) {
        return NON_STRING_ARG_PREFIX + decodeSegment(
            segment.slice(ESCAPED_STRING_ARG_PREFIX.length)
        );
    }
    if (segment.startsWith(NON_STRING_ARG_PREFIX)) {
        return JSON.parse(decodeSegment(segment.slice(NON_STRING_ARG_PREFIX.length)));
    }
    return decodeSegment(segment);
}

/**
 * Tries to parse a key content string as a structured JSON object with
 * `head` and `args` fields.  Returns the parsed object, or null if the
 * content is not valid structured key JSON.
 *
 * @param {string} keyContent
 * @returns {{ head: string, args: unknown[] } | null}
 */
function tryParseStructuredKey(keyContent) {
    if (!keyContent.startsWith('{')) {
        return null;
    }
    try {
        const parsed = JSON.parse(keyContent);
        if (
            parsed !== null &&
            typeof parsed === 'object' &&
            typeof parsed.head === 'string' &&
            Array.isArray(parsed.args)
        ) {
            return parsed;
        }
    } catch {
        // Not valid JSON
    }
    return null;
}

/**
 * Validates that a non-plain sublevel key is encoded as a structured JSON
 * object with `head` and `args` fields.  Non-plain sublevels are always
 * decoded back from filesystem paths as such JSON, so accepting arbitrary
 * raw strings here would silently corrupt keys on round-trip.
 *
 * @param {string[]} sublevels
 * @param {string} keyContent
 * @returns {{ head: string, args: unknown[] }}
 * @throws {Error} If keyContent is not valid structured key JSON for these sublevels.
 */
function requireStructuredKey(sublevels, keyContent) {
    const structuredKey = tryParseStructuredKey(keyContent);
    if (structuredKey !== null) {
        return structuredKey;
    }
    throw new Error(
        `Invalid database key content for sublevels '${sublevels.join('!!')}': expected structured JSON key, got ${keyContent}`
    );
}

/**
 * Builds the canonical JSON string stored as the key content in non-plain
 * (data) sublevels.  The produced string has the form:
 *   `{"head":"<name>","args":[...]}`
 *
 * @param {string} head - The key head name.
 * @param {unknown[]} args - The argument list.
 * @returns {string}
 */
function buildStructuredKeyContent(head, args) {
    return JSON.stringify({ head, args });
}

/**
 * Converts a raw LevelDB key to a relative filesystem path.
 *
 * For structured JSON keys stored in data sublevels (values, freshness,
 * inputs, revdeps, counters, timestamps), the stored key is decomposed into
 * human-readable path segments:
 *   namespace/sublevel/head/arg1/arg2/...
 *
 * For plain string keys stored in meta sublevels (_meta, meta), the key
 * is used as a single percent-encoded segment:
 *   namespace/sublevel/key
 *
 * The argument encoding ensures round-trip fidelity:
 *   - `/`, `%`, and `!` are percent-encoded within each segment.
 *   - Non-string values are JSON-encoded and prefixed with `~`.
 *
 * @param {string} rawKey - Raw LevelDB key.
 * @returns {string} Relative filesystem path.
 */
function keyToRelativePath(rawKey) {
    const { sublevels, keyContent } = parseRawKey(rawKey);
    const lastSublevel = sublevels[sublevels.length - 1] ?? '';
    const isPlainKey = PLAIN_KEY_SUBLEVELS.has(lastSublevel);

    if (isPlainKey) {
        return [...sublevels, encodeSegment(keyContent)].join('/');
    }

    const structuredKey = requireStructuredKey(sublevels, keyContent);
    const argSegments = structuredKey.args.map(encodeArg);
    return [...sublevels, structuredKey.head, ...argSegments].join('/');
}

/**
 * Converts a relative filesystem path back to a raw LevelDB key.
 * This is the exact inverse of keyToRelativePath().
 *
 * Depth convention:
 *   - If the first segment is `_meta` → depth 1 (1-level nesting)
 *   - Otherwise → depth 2 (2-level nesting: namespace + sublevel)
 *
 * Key type convention (determined by the last sublevel name):
 *   - `_meta` or `meta` → plain string key
 *   - All other sublevels → structured JSON key
 *
 * @param {string} relPath - Relative path from keyToRelativePath().
 * @returns {string} Raw LevelDB key.
 * @throws {Error} If relPath has fewer than two segments.
 */
function relativePathToKey(relPath) {
    const segments = relPath.split('/');
    if (segments.length < 2) {
        throw new Error(
            `Invalid database path '${relPath}': expected at least two segments.`
        );
    }

    // Determine sublevel depth from the first segment
    const depth = segments[0] === '_meta' ? 1 : 2;
    if (segments.length < depth + 1) {
        throw new Error(
            `Invalid database path '${relPath}': expected at least ${depth + 1} segments for depth-${depth} nesting.`
        );
    }

    const sublevels = segments.slice(0, depth);
    const keyComponents = segments.slice(depth);
    const lastSublevel = sublevels[sublevels.length - 1] ?? '';
    const isPlainKey = PLAIN_KEY_SUBLEVELS.has(lastSublevel);

    let keyContent;
    if (isPlainKey) {
        if (keyComponents.length !== 1) {
            throw new Error(
                `Invalid database path '${relPath}': plain-key sublevels require exactly one key segment`
            );
        }
        // key is a single plain string segment
        keyContent = decodeSegment(keyComponents[0] ?? '');
    } else {
        // key is structured: first component is head, rest are args
        const head = keyComponents[0] ?? '';
        const args = keyComponents.slice(1).map(decodeArg);
        keyContent = buildStructuredKeyContent(head, args);
    }

    return buildRawKey(sublevels, keyContent);
}

/**
 * Serialises a database value to a JSON string for storage in a snapshot file.
 * This is the write-side counterpart of parseValue().
 *
 * @param {unknown} value - The database value to serialise.
 * @returns {string} Pretty-printed JSON string.
 */
function serializeValue(value) {
    return JSON.stringify(value, null, 2);
}

/**
 * Parses a JSON string read from a snapshot file back to a database value.
 * This is the read-side counterpart of serializeValue().
 *
 * @param {string} content - The raw file content written by serializeValue.
 * @returns {unknown} The parsed value, to be stored back into the database.
 */
function parseValue(content) {
    return JSON.parse(content);
}

module.exports = {
    keyToRelativePath,
    relativePathToKey,
    serializeValue,
    parseValue,
};
