/**
 * Key encoding and value serialisation module for the incremental-graph database.
 *
 * This module converts between the two representations of a database snapshot entry:
 *
 *   - Raw LevelDB key/value pairs (what the database stores)
 *   - Filesystem path/content pairs  (what the snapshot directory stores)
 *
 * Key encoding
 * ------------
 * LevelDB sublevel keys are structured as:
 *
 *   !namespace!!sublevel!keyContent
 *
 * The `!!` separator marks the boundary between nested sublevel names.
 * The actual stored key follows after the last `!` in the prefix chain.
 *
 * Key content is treated as an opaque string regardless of what it contains
 * (it may be a JSON object, a plain string, or any other format).
 *
 * The on-disk path for a key with sublevel depth D is:
 *
 *   sub1/sub2/.../subD/<percent-encoded keyContent>
 *
 * Depth convention
 * ----------------
 * This database always uses either:
 *   - 1-level nesting: the `_meta` root sublevel
 *   - 2-level nesting: namespace (`x` or `y`) + data or meta sublevel
 *
 * Depth is inferred from the first path segment when decoding:
 * if it is `_meta`, depth = 1; otherwise depth = 2.
 *
 * Segment encoding
 * ----------------
 * Key content is encoded as a single path segment. Only characters unsafe for
 * POSIX filenames require encoding: `/` -> `%2F`, `%` -> `%25` (to avoid
 * double-encoding), `!` -> `%21` (so round-tripping preserves LevelDB structure).
 * The literal segments `.` and `..` are encoded as `%2E` and `%2E%2E` to prevent
 * directory traversal.
 *
 * Value serialisation
 * -------------------
 * Database values are serialised to JSON text when written to files
 * (serializeValue) and parsed back from JSON text when read (parseValue).
 *
 * Bijection guarantee
 * -------------------
 * For all keys generated by this database, keyToRelativePath and
 * relativePathToKey are exact inverses:
 *   relativePathToKey(keyToRelativePath(key)) === key
 */

// Use uppercase sentinels as the canonical on-disk form for literal '.' and '..'
// segments so renderToFilesystem() is deterministic; decode accepts lowercase
// too so scanFromFilesystem() stays tolerant of manually created snapshots.
const DOT_SEGMENT_SENTINEL = '%2E';
const DOT_DOT_SEGMENT_SENTINEL = '%2E%2E';
const DOT_SEGMENT_PATTERN = /^%2e$/i;
const DOT_DOT_SEGMENT_PATTERN = /^%2e%2e$/i;

/**
 * Parses a raw LevelDB key into its sublevel names and key content.
 *
 * Raw key format: `!sub1!!sub2!...!subN!keyContent`
 *
 * Algorithm:
 *   1. Strip the leading `!`.
 *   2. Split on `!!` -- all segments but the last are pure sublevel names.
 *   3. Split the last segment on the FIRST `!` to separate the deepest
 *      sublevel name from the key content.  This preserves any `!` characters
 *      that may appear inside the key content itself.
 *
 * @param {string} rawKey
 * @returns {{ sublevels: string[], keyContent: string }}
 * @throws {Error} If rawKey does not match the expected `!sublevels!key` format.
 */
function parseRawKey(rawKey) {
    if (!rawKey.startsWith('!')) {
        throw new Error(
            `Invalid database key '${rawKey}': expected raw LevelDB keys to start with '!'`
        );
    }

    /** @type {string[]} */
    const sublevels = [];
    let current = '';
    let i = 1;
    while (i < rawKey.length) {
        const character = rawKey[i];
        if (character === '!') {
            const nextCharacter = i + 1 < rawKey.length ? rawKey[i + 1] : '';
            if (current === '') {
                throw new Error(
                    `Invalid database key '${rawKey}': sublevel names must not be empty.`
                );
            }
            if (nextCharacter === '!') {
                sublevels.push(current);
                current = '';
                i += 2;
                continue;
            } else {
                sublevels.push(current);
                return { sublevels, keyContent: rawKey.slice(i + 1) };
            }
        } else {
            current += character;
        }
        i += 1;
    }

    throw new Error(
        `Invalid database key '${rawKey}': expected a '!' separator before key content.`
    );
}

/**
 * Reconstructs a raw LevelDB key from its sublevel names and key content.
 * Inverse of parseRawKey().
 *
 * @param {string[]} sublevels - Ordered list of sublevel names.
 * @param {string} keyContent - The raw stored key content.
 * @returns {string}
 */
function buildRawKey(sublevels, keyContent) {
    return '!' + sublevels.join('!!') + '!' + keyContent;
}

/**
 * Percent-encodes a string for use as a single filesystem path segment.
 * Encodes `%` first to avoid double-encoding, then `/` and `!`.
 * Segments that are exactly `.` or `..` are mapped to sentinels so they never
 * become literal filesystem traversal segments.
 * @param {string} s
 * @returns {string}
 */
function encodeSegment(s) {
    if (s === '.') {
        return DOT_SEGMENT_SENTINEL;
    }
    if (s === '..') {
        return DOT_DOT_SEGMENT_SENTINEL;
    }
    // Encode '%' first to prevent double-encoding (e.g. '/' -> '%2F' -> '%252F').
    return s.replace(/%/g, '%25').replace(/\//g, '%2F').replace(/!/g, '%21');
}

/**
 * Decodes a percent-encoded path segment back to the original string.
 * @param {string} s
 * @returns {string}
 */
function decodeSegment(s) {
    // Accept either uppercase or lowercase sentinels when scanning a
    // filesystem snapshot, even though encodeSegment() always emits the
    // uppercase canonical sentinels defined above, so manually created
    // snapshots can still be imported reliably.
    if (DOT_SEGMENT_PATTERN.test(s)) {
        return '.';
    }
    if (DOT_DOT_SEGMENT_PATTERN.test(s)) {
        return '..';
    }
    return s.replace(/%21/gi, '!').replace(/%2F/gi, '/').replace(/%25/gi, '%');
}

/**
 * Converts a raw LevelDB key to a relative filesystem path.
 *
 * The sublevels become the directory components and the key content becomes the
 * filename, percent-encoded so it is safe to use as a single path segment.
 *
 * Examples:
 *   !_meta!format
 *     -> _meta/format
 *
 *   !x!!meta!version
 *     -> x/meta/version
 *
 *   !x!!values!{"head":"event","args":["abc"]}
 *     -> x/values/{"head":"event","args":["abc"]}
 *
 *   !x!!values!{"head":"transcription","args":["/audio/x.mp3"]}
 *     -> x/values/{"head":"transcription","args":["%2Faudio%2Fx.mp3"]}
 *
 * @param {string} rawKey - Raw LevelDB key.
 * @returns {string} Relative filesystem path.
 */
function keyToRelativePath(rawKey) {
    const { sublevels, keyContent } = parseRawKey(rawKey);
    return [...sublevels, encodeSegment(keyContent)].join('/');
}

/**
 * Converts a relative filesystem path back to a raw LevelDB key.
 * This is the exact inverse of keyToRelativePath().
 *
 * Depth convention:
 *   - If the first segment is `_meta` -> depth 1 (1-level nesting)
 *   - Otherwise -> depth 2 (2-level nesting: namespace + sublevel)
 *
 * The path must have exactly `depth + 1` segments: the sublevels followed by
 * the encoded key content as a single filename.
 *
 * @param {string} relPath - Relative path from keyToRelativePath().
 * @returns {string} Raw LevelDB key.
 * @throws {Error} If relPath does not have exactly `depth + 1` segments.
 */
function relativePathToKey(relPath) {
    const segments = relPath.split('/');
    if (segments.length < 2) {
        throw new Error(
            `Invalid database path '${relPath}': expected at least two segments.`
        );
    }

    // Determine sublevel depth from the first segment.
    const depth = segments[0] === '_meta' ? 1 : 2;
    if (segments.length !== depth + 1) {
        throw new Error(
            `Invalid database path '${relPath}': expected exactly ${depth + 1} segments for depth-${depth} nesting, got ${segments.length}.`
        );
    }

    const sublevels = segments.slice(0, depth);
    const keyContent = decodeSegment(segments[depth] ?? '');
    return buildRawKey(sublevels, keyContent);
}

/**
 * Serialises a database value to a JSON string for storage in a snapshot file.
 * This is the write-side counterpart of parseValue().
 *
 * @param {unknown} value - The database value to serialise.
 * @returns {string} Pretty-printed JSON string.
 */
function serializeValue(value) {
    return JSON.stringify(value, null, 2);
}

/**
 * Parses a JSON string read from a snapshot file back to a database value.
 * This is the read-side counterpart of serializeValue().
 *
 * @param {string} content - The raw file content written by serializeValue.
 * @returns {unknown} The parsed value, to be stored back into the database.
 */
function parseValue(content) {
    return JSON.parse(content);
}

module.exports = {
    keyToRelativePath,
    relativePathToKey,
    serializeValue,
    parseValue,
};
