/**
 * Filesystem rendering module for the incremental-graph database.
 *
 * Provides two complementary operations that form a bijective pair:
 *
 *   renderToFilesystem(capabilities, rootDatabase, outputDir)
 *     Dumps every raw LevelDB key/value pair to a directory tree.
 *     Each key is mapped to a relative file path via keyToRelativePath().
 *     Each value is written as a JSON string.
 *
 *   scanFromFilesystem(capabilities, rootDatabase, inputDir)
 *     Restores a database from a directory tree written by renderToFilesystem().
 *     First clears all existing entries in rootDatabase, then walks inputDir
 *     recursively, maps each file path back to a key via relativePathToKey(),
 *     parses the JSON content, and writes the entry into the database.
 *
 * Key encoding
 * ------------
 * LevelDB sublevel keys are structured as:
 *
 *   !namespace!!sublevel!{"head":"all_events","args":[]}
 *
 * The `!!` separator marks the boundary between nested sublevel names.
 * The actual stored key follows after the last `!` in the prefix chain.
 *
 * Two types of stored key exist in this database:
 *
 *   1. NodeKey JSON (data sublevels: values, freshness, inputs, revdeps,
 *      counters, timestamps):
 *        {"head":"event","args":["abc"]}
 *      Encoded as: namespace/sublevel/event/abc
 *
 *   2. Plain string (meta sublevels: _meta, meta):
 *        format, version
 *      Encoded as: namespace/sublevel/format
 *
 * Argument encoding
 * -----------------
 * String arguments are percent-encoded: `/` → `%2F`, `%` → `%25`,
 * `!` → `%21` (critical for bijection since `!` is the LevelDB separator).
 * Non-string arguments (numbers, booleans, arrays, objects) are JSON-encoded
 * and prefixed with `~` to distinguish them from plain strings.
 *
 * Depth convention
 * ----------------
 * This database always uses either:
 *   - 1-level nesting: the `_meta` root sublevel (plain string keys)
 *   - 2-level nesting: namespace (`x` or `y`) → data or meta sublevel
 *
 * When scanning from the filesystem, the depth is inferred from the first
 * path segment: if it is `_meta`, depth = 1; otherwise depth = 2.
 *
 * Bijection guarantee
 * -------------------
 * For all keys generated by this database, keyToRelativePath and
 * relativePathToKey are exact inverses:
 *   relativePathToKey(keyToRelativePath(key)) === key
 */

const path = require('path');
const { nodeKeyStringToString } = require('./types');

/** @typedef {import('./root_database').RootDatabase} RootDatabase */
/** @typedef {import('./types').NodeKeyString} NodeKeyString */
/** @typedef {import('../../../filesystem/creator').FileCreator} FileCreator */
/** @typedef {import('../../../filesystem/writer').FileWriter} FileWriter */
/** @typedef {import('../../../filesystem/reader').FileReader} FileReader */
/** @typedef {import('../../../filesystem/checker').FileChecker} FileChecker */
/** @typedef {import('../../../filesystem/dirscanner').DirScanner} DirScanner */
/** @typedef {import('../../../filesystem/deleter').FileDeleter} FileDeleter */
/** @typedef {import('../../../logger').Logger} Logger */

/**
 * Capabilities required by renderToFilesystem and scanFromFilesystem.
 * @typedef {object} RenderCapabilities
 * @property {FileCreator} creator - Creates files (and parent directories) on disk.
 * @property {FileWriter} writer - Writes string content to an existing file.
 * @property {FileReader} reader - Reads file content as a UTF-8 string.
 * @property {FileChecker} checker - Checks whether a path is a file or directory.
 * @property {DirScanner} scanner - Scans directory contents (non-recursive).
 * @property {FileDeleter} deleter - Deletes files or directories.
 * @property {Logger} logger - Logger for progress messages.
 */

/**
 * Sublevel names that store plain string keys rather than NodeKey JSON.
 * @type {Set<string>}
 */
const PLAIN_KEY_SUBLEVELS = new Set(['_meta', 'meta']);

/**
 * Prefix used to distinguish non-string ConstValue arguments from plain strings.
 * A path segment starting with '~' holds a JSON-encoded non-string value.
 */
const NON_STRING_ARG_PREFIX = '~';
const ESCAPED_STRING_ARG_PREFIX = NON_STRING_ARG_PREFIX + NON_STRING_ARG_PREFIX;

/**
 * Parses a raw LevelDB key into its sublevel names and key content.
 *
 * Raw key format: `!sub1!!sub2!...!subN!keyContent`
 *
 * Algorithm:
 *   1. Strip the leading `!`.
 *   2. Split on `!!` — all segments but the last are pure sublevel names.
 *   3. Split the last segment on the FIRST `!` to separate the deepest
 *      sublevel name from the key content.  This preserves any `!` characters
 *      that may appear inside the key content itself.
 *
 * @param {string} rawKey
 * @returns {{ sublevels: string[], keyContent: string }}
 * @throws {Error} If rawKey does not match the expected `!sublevels!key` format.
 */
function parseRawKey(rawKey) {
    if (!rawKey.startsWith('!')) {
        throw new Error(
            `Invalid database key '${rawKey}': expected raw LevelDB keys to start with '!'`
        );
    }

    /** @type {string[]} */
    const sublevels = [];
    let current = '';
    let i = 1;
    while (i < rawKey.length) {
        const character = rawKey[i];
        if (character === '!') {
            const nextCharacter = i + 1 < rawKey.length ? rawKey[i + 1] : '';
            if (current === '') {
                throw new Error(
                    `Invalid database key '${rawKey}': sublevel names must not be empty.`
                );
            }
            if (nextCharacter === '!') {
                sublevels.push(current);
                current = '';
                i += 2;
                continue;
            } else {
                sublevels.push(current);
                return { sublevels, keyContent: rawKey.slice(i + 1) };
            }
        } else {
            current += character;
        }
        i += 1;
    }

    throw new Error(
        `Invalid database key '${rawKey}': expected a '!' separator before key content.`
    );
}

/**
 * Reconstructs a raw LevelDB key from its sublevel names and key content.
 * Inverse of parseRawKey().
 *
 * @param {string[]} sublevels - Ordered list of sublevel names.
 * @param {string} keyContent - The raw stored key content.
 * @returns {string}
 */
function buildRawKey(sublevels, keyContent) {
    return '!' + sublevels.join('!!') + '!' + keyContent;
}

/**
 * Percent-encodes a plain string for use as a single filesystem path segment.
 * Encodes `%` first to avoid double-encoding, then `/` and `!`.
 * @param {string} s
 * @returns {string}
 */
function encodeSegment(s) {
    // Encode '%' first to prevent double-encoding (e.g. '/' → '%2F' → '%252F').
    return s.replace(/%/g, '%25').replace(/\//g, '%2F').replace(/!/g, '%21');
}

/**
 * Decodes a percent-encoded path segment back to the original string.
 * @param {string} s
 * @returns {string}
 */
function decodeSegment(s) {
    return s.replace(/%21/gi, '!').replace(/%2F/gi, '/').replace(/%25/gi, '%');
}

/**
 * Encodes a ConstValue argument as a path segment.
 *
 * String arguments are percent-encoded directly.
 * Non-string arguments (number, boolean, null, array, object) are
 * JSON-serialized and prefixed with NON_STRING_ARG_PREFIX (`~`) so they
 * can be distinguished from plain strings during decoding.
 *
 * @param {*} arg - A ConstValue argument.
 * @returns {string}
 */
function encodeArg(arg) {
    if (typeof arg === 'string') {
        if (arg.startsWith(NON_STRING_ARG_PREFIX)) {
            // Escape a leading '~' in string args so "~42" stays distinct from
            // the encoded non-string number 42, which is also prefixed with '~'.
            return ESCAPED_STRING_ARG_PREFIX + encodeSegment(arg.slice(1));
        }
        return encodeSegment(arg);
    }
    return NON_STRING_ARG_PREFIX + encodeSegment(JSON.stringify(arg));
}

/**
 * Decodes a path segment back to a ConstValue argument.
 * Inverse of encodeArg().
 *
 * @param {string} segment
 * @returns {*}
 */
function decodeArg(segment) {
    if (segment.startsWith(ESCAPED_STRING_ARG_PREFIX)) {
        return NON_STRING_ARG_PREFIX + decodeSegment(
            segment.slice(ESCAPED_STRING_ARG_PREFIX.length)
        );
    }
    if (segment.startsWith(NON_STRING_ARG_PREFIX)) {
        return JSON.parse(decodeSegment(segment.slice(NON_STRING_ARG_PREFIX.length)));
    }
    return decodeSegment(segment);
}

/**
 * Tries to parse a string as a NodeKey JSON object.
 * Returns the parsed NodeKey, or null if the string is not a valid NodeKey.
 *
 * @param {string} keyContent
 * @returns {{ head: string, args: Array<*> } | null}
 */
function tryParseNodeKey(keyContent) {
    if (!keyContent.startsWith('{')) {
        return null;
    }
    try {
        const parsed = JSON.parse(keyContent);
        if (
            parsed !== null &&
            typeof parsed === 'object' &&
            typeof parsed.head === 'string' &&
            Array.isArray(parsed.args)
        ) {
            return parsed;
        }
    } catch {
        // Not valid JSON
    }
    return null;
}

/**
 * Validates that a non-plain sublevel key is encoded as a NodeKey JSON object.
 * Non-plain sublevels are always decoded back from filesystem paths as NodeKey
 * JSON, so accepting arbitrary raw strings here would silently corrupt keys on
 * round-trip.
 *
 * @param {string[]} sublevels
 * @param {string} keyContent
 * @returns {{ head: string, args: Array<*> }}
 * @throws {Error} If keyContent is not valid NodeKey JSON for these sublevels.
 */
function requireNodeKey(sublevels, keyContent) {
    const nodeKey = tryParseNodeKey(keyContent);
    if (nodeKey !== null) {
        return nodeKey;
    }
    throw new Error(
        `Invalid database key content for sublevels '${sublevels.join('!!')}': expected NodeKey JSON, got ${keyContent}`
    );
}

/**
 * Converts a raw LevelDB key to a relative filesystem path.
 *
 * For NodeKey JSON stored in data sublevels (values, freshness, inputs,
 * revdeps, counters, timestamps), the stored key is decomposed into
 * human-readable path segments:
 *   namespace/sublevel/head/arg1/arg2/...
 *
 * For plain string keys stored in meta sublevels (_meta, meta), the key
 * is used as a single percent-encoded segment:
 *   namespace/sublevel/key
 *
 * The argument encoding ensures round-trip fidelity:
 *   - `/`, `%`, and `!` are percent-encoded within each segment.
 *   - Non-string values are JSON-encoded and prefixed with `~`.
 *
 * @param {string} rawKey - Raw LevelDB key.
 * @returns {string} Relative filesystem path.
 */
function keyToRelativePath(rawKey) {
    const { sublevels, keyContent } = parseRawKey(rawKey);
    const lastSublevel = sublevels[sublevels.length - 1] ?? '';
    const isPlainKey = PLAIN_KEY_SUBLEVELS.has(lastSublevel);

    if (isPlainKey) {
        return [...sublevels, encodeSegment(keyContent)].join('/');
    }

    const nodeKey = requireNodeKey(sublevels, keyContent);
    const argSegments = nodeKey.args.map(encodeArg);
    return [...sublevels, nodeKey.head, ...argSegments].join('/');
}

/**
 * Converts a relative filesystem path back to a raw LevelDB key.
 * This is the exact inverse of keyToRelativePath().
 *
 * Depth convention:
 *   - If the first segment is `_meta` → depth 1 (1-level nesting)
 *   - Otherwise → depth 2 (2-level nesting: namespace + sublevel)
 *
 * Key type convention (determined by the last sublevel name):
 *   - `_meta` or `meta` → plain string key
 *   - All other sublevels → NodeKey JSON key
 *
 * @param {string} relPath - Relative path from keyToRelativePath().
 * @returns {string} Raw LevelDB key.
 * @throws {Error} If relPath has fewer than two segments.
 */
function relativePathToKey(relPath) {
    const segments = relPath.split('/');
    if (segments.length < 2) {
        throw new Error(
            `Invalid database path '${relPath}': expected at least two segments.`
        );
    }

    // Determine sublevel depth from the first segment
    const depth = segments[0] === '_meta' ? 1 : 2;
    if (segments.length < depth + 1) {
        throw new Error(
            `Invalid database path '${relPath}': expected at least ${depth + 1} segments for depth-${depth} nesting.`
        );
    }

    const sublevels = segments.slice(0, depth);
    const keyComponents = segments.slice(depth);
    const lastSublevel = sublevels[sublevels.length - 1] ?? '';
    const isPlainKey = PLAIN_KEY_SUBLEVELS.has(lastSublevel);

    let keyContent;
    if (isPlainKey) {
        if (keyComponents.length !== 1) {
            throw new Error(
                `Invalid database path '${relPath}': plain-key sublevels require exactly one key segment`
            );
        }
        // key is a single plain string segment
        keyContent = decodeSegment(keyComponents[0] ?? '');
    } else {
        // key is a NodeKey: first component is head, rest are args
        const head = keyComponents[0] ?? '';
        const args = keyComponents.slice(1).map(decodeArg);
        keyContent = JSON.stringify({ head, args });
    }

    return buildRawKey(sublevels, keyContent);
}

/**
 * Removes a previous rendered snapshot directory if it exists.
 * This prevents stale files from surviving across repeated renders into the
 * same output directory when the database shrinks between snapshots.
 *
 * @param {RenderCapabilities} capabilities
 * @param {string} outputDir
 * @returns {Promise<void>}
 */
async function clearRenderedSnapshot(capabilities, outputDir) {
    if (await capabilities.checker.directoryExists(outputDir)) {
        await capabilities.deleter.deleteDirectory(outputDir);
    }
}

/**
 * Recursively collects the absolute paths of every regular file under `dir`
 * using the capabilities pattern.
 * Directories are traversed but not included in the result.
 *
 * @param {RenderCapabilities} capabilities
 * @param {string} dir - Root directory to walk.
 * @returns {Promise<string[]>} Absolute paths of all files found.
 */
async function walkFilesRecursively(capabilities, dir) {
    const children = await capabilities.scanner.scanDirectory(dir);
    const files = [];
    for (const child of children) {
        // Prevent traversal outside the current directory (for example via symlinks).
        const relative = path.relative(dir, child.path);
        if (relative === '..' || relative.startsWith('..' + path.sep)) {
            continue;
        }

        if (await capabilities.checker.directoryExists(child.path)) {
            const nested = await walkFilesRecursively(capabilities, child.path);
            files.push(...nested);
        } else if (await capabilities.checker.fileExists(child.path)) {
            files.push(child.path);
        }
    }
    return files;
}

/**
 * Dumps every raw key/value pair from a LevelDB database to a directory tree.
 *
 * For each entry in the database:
 *   - The key is mapped to a relative file path via keyToRelativePath().
 *   - The value is JSON-serialised and written to that file.
 *
 * Parent directories are created automatically.  The output directory itself
 * is also created if it does not already exist.
 *
 * This function is the inverse of scanFromFilesystem().
 *
 * @param {RenderCapabilities} capabilities
 * @param {RootDatabase} rootDatabase - The database to dump.
 * @param {string} outputDir - Absolute path of the directory to write into.
 * @returns {Promise<void>}
 */
async function renderToFilesystem(capabilities, rootDatabase, outputDir) {
    /** @type {{ relPath: string, value: any }[]} */
    const validatedEntries = [];
    for await (const [key, value] of rootDatabase._rawEntries()) {
        const relPath = keyToRelativePath(nodeKeyStringToString(key));
        validatedEntries.push({ relPath, value });
    }

    await clearRenderedSnapshot(capabilities, outputDir);
    for (const entry of validatedEntries) {
        const absPath = path.join(outputDir, entry.relPath);
        const file = await capabilities.creator.createFile(absPath);
        await capabilities.writer.writeFile(file, JSON.stringify(entry.value));
    }
    capabilities.logger.logInfo(
        { outputDir, count: validatedEntries.length },
        'Rendered database to filesystem'
    );
}

/**
 * Reads every file from a directory tree and writes the corresponding
 * key/value pairs into a LevelDB database.
 *
 * This function FIRST clears all existing entries from rootDatabase, then
 * imports the snapshot from inputDir.  This guarantees that keys present in
 * the database but absent from the snapshot (i.e., deleted entries) do not
 * survive, preserving the bijection guarantee.
 *
 * For each file found under `inputDir`:
 *   - The path relative to `inputDir` is converted back to a raw LevelDB
 *     key via relativePathToKey().
 *   - The file content is parsed as JSON and stored at that key.
 *
 * Calling scanFromFilesystem() on a directory produced by renderToFilesystem()
 * restores the database to exactly its original state (bijection guarantee).
 *
 * @param {RenderCapabilities} capabilities
 * @param {RootDatabase} rootDatabase - The database to populate.
 * @param {string} inputDir - Absolute path of the directory to read from.
 * @returns {Promise<void>}
 */
async function scanFromFilesystem(capabilities, rootDatabase, inputDir) {
    // Phase 1: Walk, read, and parse all entries before mutating the database.
    const allFiles = await walkFilesRecursively(capabilities, inputDir);

    // Use plain string keys here because relativePathToKey reconstructs raw
    // root-level LevelDB keys, including sublevel prefixes such as `!x!!values!...`.
    /** @type {{ key: string, value: any }[]} */
    const entries = [];
    let count = 0;

    for (const absPath of allFiles) {
        const relPath = path.relative(inputDir, absPath);
        const normalizedRelPath = relPath.split(path.sep).join('/');
        const key = relativePathToKey(normalizedRelPath);
        const content = await capabilities.reader.readFileAsText(absPath);
        const value = JSON.parse(content);
        entries.push({ key, value });
        count++;
    }

    // Phase 2: After successful validation, clear and repopulate the database.
    await rootDatabase._rawDeleteAll();
    for (const entry of entries) {
        await rootDatabase._rawPut(entry.key, entry.value);
    }
    capabilities.logger.logInfo(
        { inputDir, count },
        'Scanned database from filesystem'
    );
}

module.exports = {
    renderToFilesystem,
    scanFromFilesystem,
    keyToRelativePath,
    relativePathToKey,
};
