version: "3.9"
services:
  dev:
    # build from the root Dockerfile
    build:
      context: ..
      dockerfile: Dockerfile
      # bind-mount your whole workspace for live edits
      volumes:
        - ..:/workspace:cached
        # If you use a .env file in the repo root, uncomment:
        # - ../.env:/workspace/.env:cached
        # map both frontend + backend ports
        ports:
          - "3000:3000"   # backend
          - "5173:5173"   # Vite frontend
          # pass in any env-vars you need for local dev
          environment:
            - VOLODYSLAV_SERVER_PORT=3000
            - VOLODYSLAV_OPENAI_API_KEY=${VOLODYSLAV_OPENAI_API_KEY}
            - MY_ROOT=/workspace/uploads
            # start your dev script
            command: npm run dev
