#! /bin/sh

set -e

if test "$#" -neq 1
then
    echo "Usage: $0 PREFIX" >&2
    echo 'Builds the project and installs it at location `PREFIX`.' >&2
    exit 1
fi

PREFIX="$1"
shift

test "$#" = 0

cd -- "${0%/*}"/..
set -xe

npm ci
npm run build
sh scripts/link "$PREFIX"
