#! /bin/sh

set -e

cd -- "${0%/*}"/..

if ! test "$#" = 2
then
    echo "Usage: $0 <source-directory> <prefix>" >&2
    exit 1
fi

set -xe

# Capture the version from the source repository and store it for the installed version
if command -v git >/dev/null 2>&1
then
    VERSION=$(git describe 2>/dev/null || echo "unknown")
else
    echo "This program requires git to capture the version, but git is not installed." >&2
    exit 1
fi

SOURCEDIR="$1"
shift

PREFIX="$1"
shift

BINDIR="$PREFIX"/bin

echo "$VERSION" > "$SOURCEDIR"/VERSION

# Store the full VOLODYSLAV_BASEURL for the installed version
printf '%s' "${VOLODYSLAV_BASEURL:-}" > "$SOURCEDIR"/BASE_PATH

ln -srfT -- "$SOURCEDIR"/scripts/run-main "$BINDIR"/volodyslav
