#! /bin/sh

set -ex

cd -- "${0%/*}"/..

MAYBE_PONG=$(curl --silent "http://$PHONE_LOCAL_SERVER/api/ping" 2>/dev/null || true)

if test "$MAYBE_PONG" = "pong"
then
    echo 'Server already running.' 1>&2
    exit 0
fi

npm run start -w backend
