#! /bin/sh

set -e

cd -- "${0%/*}"/..

set -xe

PREFIX="$1"
shift

git checkout master
git pull origin master --tags
npm ci
npm test
npm run build

mkdir -p "$PREFIX"/bin
ln -srfT -- "$PWD/scripts/run-main" "$PREFIX"/bin/volodyslav
