/**
 * Pending live diary questions retrieval.
 *
 * Provides the `getPendingQuestions` function used by the route layer to fetch and
 * consume questions generated by the live diary pipeline.
 *
 * @module live_diary/pending_questions
 */

const { readPendingQuestions, clearPendingQuestions } = require("./session_state");

/** @typedef {import('../temporary').Temporary} Temporary */
/** @typedef {import('../logger').Logger} Logger */

/**
 * @typedef {object} Capabilities
 * @property {Temporary} temporary
 * @property {Logger} logger
 */

/**
 * Fetch and clear pending live diary questions for a session.
 *
 * Returns all questions that have been generated since the last call.
 * The pending list is cleared atomically so each question is returned at most once.
 *
 * @param {Capabilities} capabilities
 * @param {string} sessionId
 * @returns {Promise<Array<{text: string, intent: string}>>}
 */
async function getPendingQuestions(capabilities, sessionId) {
    const { temporary } = capabilities;
    const questions = await readPendingQuestions(temporary, sessionId);
    if (questions.length > 0) {
        await clearPendingQuestions(temporary, sessionId);
        capabilities.logger.logDebug(
            { sessionId, count: questions.length },
            "Live diary pending questions fetched and cleared"
        );
    }
    return questions;
}

module.exports = {
    getPendingQuestions,
};
