name: termux
on: push

jobs:
  termux-arm64-native:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v3
      - name: Build the Termux Docker image
        run: |
          docker build --file scripts/termux.dockerfile --tag termux-ci-test .
      - name: Run Termux (arm64)
        run: |
          docker run \
            --rm \
            --security-opt seccomp:unconfined \
            -- termux-ci-test
